<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.0" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
      <PackageReference Include="xunit" Version="2.8.0" />
      <PackageReference Include="xunit.runner.visualstudio" Version="2.8.0" />
      <PackageReference Include="coverlet.collector" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/CodeGreen.csproj" />
  </ItemGroup>

</Project>
