name: Backend CI/CD

on:
  push:
    branches: [ "main", "78-cicd" ]
    paths:
      - 'Backend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./Backend

jobs:
  build_test_deploy:
    name: Build, Test, and Deploy
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Restore dependencies
      run: |
        dotnet restore src/CodeGreen.csproj
        dotnet restore tests/Backend.Tests/Backend.Tests.csproj

    - name: Build
      run: |
        dotnet build src/CodeGreen.csproj --no-restore --configuration Release
        dotnet build tests/Backend.Tests/Backend.Tests.csproj --no-restore --configuration Release

    - name: Run Unit Tests
      run: dotnet test tests/Backend.Tests/Backend.Tests.csproj --no-build --verbosity normal --configuration Release

    - name: Publish Artifacts
      run: dotnet publish src/CodeGreen.csproj -c Release -o /var/www/code-green-backend

    - name: Restart Application
      run: |
        echo "Restarting the backend service..."
        sudo systemctl restart codegreen